version: "3.3"

services:
    db:
        image: postgres:12
        container_name: postgres_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - postgres_backup:/backup
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: netology_db
        ports:
            - 5432:5432
volumes:
    postgres_data:
    postgres_backup:
